stages:
  - build

variables:
  DOCKER_REGISTRY: $CI_REGISTRY
  IMAGE: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:latest
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $IMAGE
      --cache=true
      --cache-repo=$CI_REGISTRY_IMAGE/cache
