stages:
  - build

variables:
  DOCKER_REGISTRY: $CI_REGISTRY
  IMAGE: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - echo "Building the app..."
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor \
      --context "${CI_PROJECT_DIR}" \
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
      --destination "${IMAGE}:${CI_COMMIT_TAG}" \
      --destination "${IMAGE}:latest"
